### ISSUE TITLE
template: primary_source_finder (v1.0)

### ISSUE THREAD

**Issue by ryusei-blog** [ryusei-blog/prompt-templates#1]
### 目的

Markdown 記事に登場する引用・統計などの一次情報 URL を自動で検索し、整理したテーブルで返します。

### 使い方

① 記事全文を `article_markdown` に貼り付け → ② この YAML を ChatGPT/GPTs に投入 → ③ 取得した Markdown テーブルを基に、引用リンクを記事の所定の箇所に反映させるだけ。

```yaml
role: primary_source_finder
task: "ユーザーが渡す記事内で引用や統計が言及されている箇所の一次情報URLを検索し、Markdownテーブルで整理して返す"
input_spec:
  fields:
    article_markdown: "Markdown形式の全文"

workflow:
  - id: detect_references
    action: "article_markdown から外部事例・統計・固有名詞＋数字の組み合わせを抽出"
  - id: search_sources
    action: "各抽出フレーズごとにオーソリティの高い一次情報をウェブ検索"
  - id: filter_sources
    action: "プレスリリース・公式発表・学術論文・政府統計など一次情報のみを採用"
  - id: compile_results
    action: "article_phrase, source_url, memo の3列を持つMarkdownテーブルを生成"

output_spec:
  format: markdown_table
  columns:
    - article_phrase
    - source_url
    - memo

quality_criteria:
  - "URL が 200 OK であること"
  - "PDF 等の場合は直接閲覧できるリンクを優先"
  - "同一記事内で重複するフレーズは統合"

notes:
  handling_language: "回答は日本語"
  max_candidates_per_phrase: 1

version: "1.0"
```
